name: property_scan_pro
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.5.0
  #device_info_plus: ^10.1.0
  connectivity_plus: ^6.0.3
  #nb_utils: ^7.0.2
  sizer: ^2.0.15
  intl: ^0.19.0
  get: ^4.6.6
  pinput: ^4.0.0
  country_picker: ^2.0.27
  http: ^1.2.1
  google_fonts: ^6.1.0
  #flutter_inappwebview: ^6.0.0
  webview_flutter: ^4.7.0
  #flutter_inappwebview: ^5.8.0
  url_launcher: ^6.3.1
  get_secure_storage: ^1.0.5
  shimmer: ^3.0.0
  share_plus: ^10.1.2
  flutter_fortune_wheel: ^1.3.1
  carousel_slider: ^5.0.0
  dropdown_button2: ^2.3.9
  flutter_timezone: ^3.0.1
  glowy_borders: ^1.0.2


  #Image&PDF
  cached_network_image: ^3.3.1
  permission_handler: ^11.3.1
  flutter_svg: ^2.0.16


  #video player
  video_player: ^2.10.0
  chewie: any
  audioplayers: ^6.0.0
  flutter_screen_recording: ^2.0.24
  record: ^6.1.2
  ffmpeg_kit_flutter_new: ^4.1.0
  pdf: ^3.11.3
  flutter_pdfview: ^1.4.1+1
  sqflite: ^2.4.2
  #water_drop_nav_bar: ^2.2.2

  #Firebase
  #firebase_core: ^3.8.0
  firebase_core: ^4.3.0
  #firebase_messaging: ^15.1.5
  firebase_messaging: ^16.1.0
  flutter_local_notifications: ^19.5.0
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1
  firebase_auth: any
  flutter_roomplan: ^1.0.7
  #model_viewer_plus: any
  #file_picker: any
  flutter_viewer_usdz: ^0.0.7
#  video_compress: ^3.1.4
  syncfusion_flutter_pdfviewer: any


  #File Manager
  #file_picker: ^8.0.3
  image_picker: ^1.1.2
  crop_image: ^1.0.15
  #image: ^4.5.0
  image: any
  path: ^1.9.0
  path_provider: ^2.1.3
  #flutter_email_sender: ^6.0.3
  open_file_manager: ^1.0.2
  video_thumbnail: ^0.5.3
  crypto: ^3.0.3


  #lottie
  lottie: ^3.1.1

  in_app_review: ^2.0.9
  flutter_upgrade_version: ^1.1.8
  google_nav_bar: ^5.0.7
  ultralytics_yolo:
    path: ultralytics_yolo


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_widget_from_html_core: ^0.16.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/models/
    - assets/models/best.mlpackage/
    - assets/models/best-new.mlpackage/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Afacad
      fonts:
        - asset: fonts/Afacad-Regular.ttf
        - asset: fonts/Afacad-Italic.ttf
        - asset: fonts/Afacad-Medium.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
